name: Android Automation Tests (AWS Device Farm)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  device-farm-run:
    name: Build APK and run tests on AWS Device Farm
    runs-on: ubuntu-latest
    # NOTE: keep workflow minimal — only values actually used by the scripts

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Instalar dependências
      run: npm ci

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Android APK (Gradle)
      working-directory: app/android
      run: |
        chmod +x gradlew || true
        ./gradlew assembleDebug --no-daemon

    - name: Prepare test package (zip)
      run: |
        echo "Preparando pacote de testes..."
        rm -f tests.zip
        # Incluir package.json, wdio config e pasta de testes
        zip -r tests.zip package.json package-lock.json wdio.conf.ts test || true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install AWS CLI and utilities
      run: |
        sudo apt-get update -y
        sudo apt-get install -y jq zip unzip
        python3 -m pip install --upgrade awscli

    - name: Upload APK to Device Farm
      id: upload_app
      run: |
        set -e
        PROJECT_ARN=${{ secrets.DEVICE_FARM_PROJECT_ARN }}
        APK_PATH="app/android/app/build/outputs/apk/debug/app-debug.apk"
        if [ -f "$APK_PATH" ]; then
          APK_FILE="$APK_PATH"
        else
          APK_FILE=$(find . -name "*.apk" | head -n 1)
        fi
        echo "Usando APK: $APK_FILE"
        UPLOAD_JSON=$(aws devicefarm create-upload --project-arn "$PROJECT_ARN" --name "$(basename $APK_FILE)" --type ANDROID_APP)
        APP_UPLOAD_ARN=$(echo "$UPLOAD_JSON" | jq -r '.upload.arn')
        APP_UPLOAD_URL=$(echo "$UPLOAD_JSON" | jq -r '.upload.url')
        curl -T "$APK_FILE" "$APP_UPLOAD_URL"
        # Poll upload status
        for i in $(seq 1 120); do
          status=$(aws devicefarm get-upload --arn "$APP_UPLOAD_ARN" --query upload.status --output text)
          echo "Upload status: $status"
          if [ "$status" = "SUCCEEDED" ]; then break; fi
          if [ "$status" = "FAILED" ]; then echo "Upload do APK falhou"; exit 1; fi
          sleep 10
        done
        echo "app_upload_arn=$APP_UPLOAD_ARN" >> $GITHUB_OUTPUT

    - name: Upload test package to Device Farm
      id: upload_tests
      run: |
        set -e
        PROJECT_ARN=${{ secrets.DEVICE_FARM_PROJECT_ARN }}
        TEST_ZIP=tests.zip
        if [ ! -f "$TEST_ZIP" ]; then echo "Arquivo de testes $TEST_ZIP não encontrado"; exit 1; fi
        UPLOAD_JSON=$(aws devicefarm create-upload --project-arn "$PROJECT_ARN" --name "${TEST_ZIP}" --type APPIUM_NODE_TEST_PACKAGE)
        TEST_UPLOAD_ARN=$(echo "$UPLOAD_JSON" | jq -r '.upload.arn')
        TEST_UPLOAD_URL=$(echo "$UPLOAD_JSON" | jq -r '.upload.url')
        curl -T "$TEST_ZIP" "$TEST_UPLOAD_URL"
        for i in $(seq 1 120); do
          status=$(aws devicefarm get-upload --arn "$TEST_UPLOAD_ARN" --query upload.status --output text)
          echo "Test upload status: $status"
          if [ "$status" = "SUCCEEDED" ]; then break; fi
          if [ "$status" = "FAILED" ]; then echo "Upload dos testes falhou"; exit 1; fi
          sleep 10
        done
        echo "test_upload_arn=$TEST_UPLOAD_ARN" >> $GITHUB_OUTPUT

    - name: Schedule Device Farm run
      id: schedule_run
      run: |
        set -e
        PROJECT_ARN=${{ secrets.DEVICE_FARM_PROJECT_ARN }}
        DEVICE_POOL_ARN=${{ secrets.DEVICE_FARM_DEVICE_POOL_ARN }}
        APP_UPLOAD_ARN=${{ steps.upload_app.outputs.app_upload_arn }}
        TEST_UPLOAD_ARN=${{ steps.upload_tests.outputs.test_upload_arn }}
        RUN_NAME="GitHubActions-$GITHUB_RUN_ID"
        echo "Agendando run: $RUN_NAME"
        RUN_JSON=$(aws devicefarm schedule-run --project-arn "$PROJECT_ARN" --app-arn "$APP_UPLOAD_ARN" --device-pool-arn "$DEVICE_POOL_ARN" --name "$RUN_NAME" --test type=APPIUM_NODE_TEST_PACKAGE,testPackageArn="$TEST_UPLOAD_ARN")
        RUN_ARN=$(echo "$RUN_JSON" | jq -r '.run.arn')
        echo "run_arn=$RUN_ARN" >> $GITHUB_OUTPUT

    - name: Wait for Device Farm run to complete
      run: |
        set -e
        RUN_ARN=${{ steps.schedule_run.outputs.run_arn }}
        echo "Aguardando conclusão do run: $RUN_ARN"
        for i in $(seq 1 120); do
          status=$(aws devicefarm get-run --arn "$RUN_ARN" --query run.status --output text)
          result=$(aws devicefarm get-run --arn "$RUN_ARN" --query run.result --output text)
          echo "status=$status result=$result"
          if [ "$status" = "COMPLETED" ]; then
            echo "Run finalizado com resultado: $result"
            if [ "$result" != "PASSED" ]; then exit 1; fi
            break
          fi
          if [ "$status" = "ERRORED" ] || [ "$status" = "PENDING" -a $i -eq 120 ]; then
            echo "Run terminou em estado inesperado: $status"
            exit 1
          fi
          sleep 10
        done

    - name: Download artifacts (optional)
      if: always()
      run: |
        echo "Se quiser baixar artefatos, use 'aws devicefarm list-artifacts' com o run ARN"
